[2025-03-22 13:31:45,830] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:26,933] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:26] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:27,152] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:27] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:27,153] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:27] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:27,155] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:27] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:27,537] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:27] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:32:27,564] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:32:27] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:07,734] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:07,735] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:07,737] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,198] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,440] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,457] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,464] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,631] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:11,639] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:11] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:33:20,138] ERROR log_exception() L875  Exception on /vehicule [DELETE] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 92, in del_produto
    vehicule_id = unquote(unquote(query.id))
                          ~~~~~~~^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python313\Lib\urllib\parse.py", line 704, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
[2025-03-22 13:33:20,246] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:33:20] "[35m[1mDELETE /vehicule?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:35:24,711] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:35:24,869] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:41:43,712] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:41:43,884] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:41:45,520] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:41:51,881] ERROR log_exception() L875  Exception on /vehicule [DELETE] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 92, in del_produto
    vehicule_id = int(unquote(unquote(query.id)))
                              ~~~~~~~^^^^^^^^^^
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python313\Lib\urllib\parse.py", line 704, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
[2025-03-22 13:41:51,890] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:41:51] "[35m[1mDELETE /vehicule?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:09,654] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:09,814] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:19,971] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:20,124] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:21,802] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:24,353] INFO _log() L97   127.0.0.1 - - [22/Mar/2025 13:44:24] "[35m[1mDELETE /vehicule?id=1 HTTP/1.1[0m" 500 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:59,437] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\schemas\\vehicule.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:44:59,615] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:45:02,337] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\schemas\\vehicule.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-03-22 13:45:02,497] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
