[2025-04-05 16:16:19,811] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:26,948] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\rescue_point.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:27,097] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:28,846] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:34,827] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\rescue_point.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:34,969] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:43,942] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\model\\rescue_point.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:16:44,142] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:13,968] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:14,124] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:54,755] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:54,942] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:58,182] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:17:58,332] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:18:00,839] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:18:01,031] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:03,581] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:03,727] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:37,125] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:37,126] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:37,129] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:41,594] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:41] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:41,771] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:41] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:41,774] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:41] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:41,780] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:41] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:42,164] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:42] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:19:42,331] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:19:42] "GET /openapi/swagger/images/swagger.svg HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:01,948] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\schemas\\rescue_point.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:02,106] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:10,588] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:10,768] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:14,497] INFO _log() L97    * Detected change in 'D:\\Desenvolvimento\\PUC\\rescue-api\\app.py', reloading - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:14,656] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:22,785] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:22] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:22,995] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:22] "[36mGET /openapi/swagger/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:23,018] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:23] "[36mGET /openapi/swagger/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:23,023] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:23] "[36mGET /openapi/swagger/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:23,205] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:23] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:21:23,218] INFO _log() L97   127.0.0.1 - - [05/Apr/2025 16:21:23] "[36mGET /openapi/swagger/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-04-05 16:22:21,971] ERROR log_exception() L875  Exception on /perform-rescue [GET] - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "D:\Desenvolvimento\PUC\rescue-api\app.py", line 245, in perform_recue_point
    closest_rescue_point = RescuePoint.closest_point(vehicule, rescue_points)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RescuePoint' has no attribute 'closest_point'
[2025-04-05 16:22:57,498] INFO _log() L97    * Restarting with stat - call_trace=d:\Desenvolvimento\PUC\rescue-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
